# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

square_cpp <- function(x) {
    .Call('_mypackage_10_31_new_square_cpp', PACKAGE = 'mypackage.10.31.new', x)
}

